sudo: true
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/lightreader-arm32v7:0.1.0 -f images/lightreader/Dockerfile .
      - docker images
      - docker push $DOCKER_USERNAME/lightreader-arm32v7:0.1.0
    - stage: test
      script:
      - docker run -d -p 127.0.0.1:80:80 --name hello $DOCKER_USERNAME/lightreader-arm32v7:0.1.0
      - docker ps | grep -q hello
      - curl -vsf 'http://127.0.0.1:80/index.html' &> /dev/stdout
